#ifndef LLAVES_H_
#define LLAVES_H_

#define TAMANIO_LINEAS 38
#define LLAVE_SEGMENTO 2015
#define LLAVE_SEGMENTO_DATOS 1000
#define LLAVE_SEGMENTO_WRITERS 1010
#define LLAVE_SEGMENTO_READERS 1020
#define LLAVE_SEGMENTO_READERS_EGOISTAS 1030

#endif // LLAVES_H_

